# Generated by Django 5.2.8 on 2025-11-16 13:24

from django.db import migrations


def create_default_teacher(apps, schema_editor):
    """Create default teacher account"""
    User = apps.get_model('survey', 'User')
    
    # Check if teacher already exists
    if not User.objects.filter(email='teacher@example.com').exists():
        # Create username from email
        username = 'teacher@example.com'.split('@')[0]
        
        # Make username unique if needed
        base_username = username
        counter = 1
        while User.objects.filter(username=username).exists():
            username = f"{base_username}{counter}"
            counter += 1
        
        # Create teacher user
        User.objects.create_user(
            username='Juan',
            email='teacher@example.com',
            password='password',
            full_name='Teacher',
            role='teacher',
            is_staff=True  # Teachers need staff access
        )


def reverse_create_default_teacher(apps, schema_editor):
    """Remove default teacher account"""
    User = apps.get_model('survey', 'User')
    User.objects.filter(email='teacher@example.com').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_teacher, reverse_create_default_teacher),
    ]
