# Generated by Django 5.2.8 on 2025-11-15 13:17

from django.db import migrations


def create_default_teacher(apps, schema_editor):
    """Create a default teacher account if it doesn't exist."""
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('survey', 'Profile')
    
    # Check if teacher account already exists
    teacher_email = 'teacher@default.com'
    if not User.objects.filter(email=teacher_email).exists():
        # Create the teacher user
        teacher_user = User.objects.create_user(
            username='teacher',
            email=teacher_email,
            password='teacher123',  # Default password - should be changed in production
            first_name='Default',
            last_name='Teacher',
            is_staff=False,
            is_superuser=False
        )
        
        # Create the profile manually (signals don't run in migrations)
        profile, created = Profile.objects.get_or_create(
            user=teacher_user,
            defaults={'role': 'teacher'}
        )
        if not created:
            profile.role = 'teacher'
            profile.save()


def reverse_create_default_teacher(apps, schema_editor):
    """Remove the default teacher account."""
    User = apps.get_model('auth', 'User')
    teacher_email = 'teacher@default.com'
    try:
        teacher_user = User.objects.get(email=teacher_email)
        teacher_user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_teacher, reverse_create_default_teacher),
    ]
