# Generated by Django 5.2.8 on 2025-11-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_questionoption_survey_question_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Dropdown'), ('rating', 'Rating'), ('scale', 'Scale'), ('date', 'Date'), ('time', 'Time'), ('file_upload', 'File Upload'), ('section', 'Section'), ('heading', 'Heading'), ('paragraph', 'Paragraph')], max_length=20),
        ),
    ]
