# Generated by Django 5.2.8 on 2025-11-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_add_section_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_modifications',
            field=models.BooleanField(default=False),
        ),
    ]
