# Generated by Django 5.2.8 on 2025-11-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_survey_allow_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='awarded_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
