# Generated by Django 5.2.7 on 2025-11-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_question_points_questionresponse_awarded_points_and_more'),
        ('survey', '0008_dashboardmetrics'),
    ]

    operations = [
    ]
