# Generated by Django 5.2.8 on 2025-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_merge_20251123_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points awarded for correct answer (minimum: 1.0)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
