# Generated by Django 5.2.8 on 2025-11-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_add_archived_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='attempts_enabled',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='require_completion_in_one_sitting',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='single_attempt',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='duration_enabled',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='duration_minutes',
        ),
    ]
