# Generated by Django 5.2.7 on 2025-11-23 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_attempts_and_duration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='duration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
