# Generated by Django 5.2.8 on 2025-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_survey_duration_enabled_survey_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='date',
            field=models.DateField(),
        ),
    ]
